### ISSUE TITLE
简体中文直接变成英文

### ISSUE THREAD

**Issue by aston314** [hirakujira/ChatGPT-Grammar-Check-PopClip-Extension#1]
请支持

**Comment by hirakujira** [comment]
翻譯功能可以用 Bob 的 extension 達成

Bob 外掛：https://github.com/yetone/bob-plugin-openai-translator

Bob x PopClip：https://bobtranslate.com/guide/integration/popclip.html

**Comment by aston314** [comment]
你主的是你插件选中文操作后内容被替换中英文，我没有想使用翻译功能

**Comment by hirakujira** [comment]
懂了，你提出的是一個 issue，不是 feature request

**Comment by hirakujira** [comment]
發佈了 v0.0.3 嘗試修正此問題，但由於 ChatGPT 特性，無法 100% 保證永遠不會再出現此狀況，如果還是經常出現可以再回報
